### PR TITLE
Attempting to fix site duplication issue #2745

### PR DESCRIPTION
**Pull request by chrisala**

### CODE REVIEW

**Comment by chrisala** [comment]
@temi @salomon-j I've fixed the test now.

**Comment by salomon-j** [comment]
> @temi @salomon-j I've fixed the test now.

@chrisala can you please share the replication steps of the duplicate issue?

**Comment by chrisala** [comment]
> @chrisala can you please share the replication steps of the duplicate issue?
There is a race involved, but it's often reproducible by:
1) Find a report and add spatial data to it.  Save and reload the page.
2) Logout in a different tab.
3) Modify a value in the report and press save.
4) You'll get an error about a session timeout.  Click the link in the dialog and re login.
5) On reload you'll be presented with a message about unsaved data.   Dismiss it.
6) Press save.
7) Reload the page.  At this point there is a good chance the spatial data in the report has been duplicated.

**Comment by salomon-j** [comment]
> > @chrisala can you please share the replication steps of the duplicate issue?
> > There is a race involved, but it's often reproducible by:
> 
> 1. Find a report and add spatial data to it.  Save and reload the page.
> 2. Logout in a different tab.
> 3. Modify a value in the report and press save.
> 4. You'll get an error about a session timeout.  Click the link in the dialog and re login.
> 5. On reload you'll be presented with a message about unsaved data.   Dismiss it.
> 6. Press save.
> 7. Reload the page _without further edits_.  At this point there is a good chance the spatial data in the report has been duplicated.
> 
> Also, note you will not be able to perform all of these steps exactly if you are running this branch as the re-login mechanism has changed (step 4 opens in a new tab and step 5 won't happen), but this should reproduce it in test/staging.

Passed duplication didn't happen on local testing and I was able to replicate the duplication issue in the Test environment,

**Pull request merged**
